version: '3.3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:
  data_volume:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: larchik892/foodgram_backend
    env_file: .env
    volumes:
      - data_volume:/app/data/
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db

  frontend:
    env_file: .env
    image: larchik892/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "8000:80"
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/static/
      - media_volume:/media/